services:
  mysql_app:
    image: mysql:8.0
    container_name: hotelbooking-mysql-app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking
    ports:
      - "3308:3306"
    volumes:
      - mysql_app_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  mysql_auth:
    image: mysql:8.0
    container_name: hotelbooking-mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel_booking_auth
    ports:
      - "3309:3306"
    volumes:
      - mysql_auth_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_app_data:
  mysql_auth_data: